### ISSUE TITLE
Use with Sveltekit 

### ISSUE THREAD

**Issue by dave-calleja** [jiangfengming/svelte-pilot#1]
Is there any way this can be used with sveltekit? Even partially? Thanks!

**Comment by jiangfengming** [comment]
Could you please clarify which specific feature of Svelte Pilot you are interested in that SvelteKit doesn't provide, prompting your consideration to integrate Svelte Pilot?

**Comment by dave-calleja** [comment]
Mainly to move away from the file-system routing, even for a subsection of the site :)

**Comment by jiangfengming** [comment]
https://stackblitz.com/~/github.com/jiangfengming/sveltekit-pilot-demo

This is solely a proof of concept and should not be used in production!

**Comment by davecalleja-casumo** [comment]
This is awesome @jiangfengming! Where do you think the issues might be in production?

**Comment by jiangfengming** [comment]
When using components loaded by Svelte Pilot, you will lose access to SvelteKit's features like [loading data](https://kit.svelte.dev/docs/load) and [form actions](https://kit.svelte.dev/docs/form-actions). Also, you can't use [route guards](https://svelte-pilot.github.io/en/routing#route-guards) from Svelte Pilot, and the [$app/navigation](https://kit.svelte.dev/docs/modules#$app-navigation) will lack params information due to the use of `[...path]`. Additionally, you won't be able to use Svelte Pilot's methods like `push()`, `replace()`, and others that operate on the HTML5 History API.

I haven't thought through it in more detail, but there are certainly more issues. Deciding when to use which library's features could be problematic, and you might find yourself in a situation where you need help but can't easily find it. My suggestion would be to start a new project using the [Svelte Pilot Template](https://github.com/svelte-pilot/svelte-pilot-template) and try writing a couple of pages. You can then use a server like nginx to proxy pass these paths to the new project.
